(ns com.blogspot.sbtourist.clojure.jstat.reader_test (:use clojure.test clojure.java.io com.blogspot.sbtourist.clojure.jstat.reader))

(deftest test-full-sample
  (let [stats (jstat-reader sample 1 (resource "jstat.txt"))]
    (is (= 4 (.size stats)))

    (is (= 1.0 ((stats 1) "Timestamp")))
    (is (= 2.0 ((stats 1) "PC")))
    (is (= 3.0 ((stats 1) "PU")))
    (is (= 4.0 ((stats 1) "OC")))
    (is (= 5.0 ((stats 1) "OU")))
    (is (= 6.0 ((stats 1) "YGC")))
    (is (= 7.0 ((stats 1) "FGC")))
    (is (= 8.0 ((stats 1) "FGCT")))
    (is (= 9.0 ((stats 1) "GCT")))

    (is (= 2.0 ((stats 2) "Timestamp")))
    (is (= 3.0 ((stats 2) "PC")))
    (is (= 4.0 ((stats 2) "PU")))
    (is (= 5.0 ((stats 2) "OC")))
    (is (= 6.0 ((stats 2) "OU")))
    (is (= 7.0 ((stats 2) "YGC")))
    (is (= 8.0 ((stats 2) "FGC")))
    (is (= 9.0 ((stats 2) "FGCT")))
    (is (= 10.0 ((stats 2) "GCT")))

    (is (= 3.0 ((stats 3) "Timestamp")))
    (is (= 4.0 ((stats 3) "PC")))
    (is (= 5.0 ((stats 3) "PU")))
    (is (= 6.0 ((stats 3) "OC")))
    (is (= 7.0 ((stats 3) "OU")))
    (is (= 8.0 ((stats 3) "YGC")))
    (is (= 9.0 ((stats 3) "FGC")))
    (is (= 10.0 ((stats 3) "FGCT")))
    (is (= 11.0 ((stats 3) "GCT")))

    (is (= 4.0 ((stats 4) "Timestamp")))
    (is (= 5.0 ((stats 4) "PC")))
    (is (= 6.0 ((stats 4) "PU")))
    (is (= 7.0 ((stats 4) "OC")))
    (is (= 8.0 ((stats 4) "OU")))
    (is (= 9.0 ((stats 4) "YGC")))
    (is (= 10.0 ((stats 4) "FGC")))
    (is (= 11.0 ((stats 4) "FGCT")))
    (is (= 12.0 ((stats 4) "GCT")))
    )
  )

(deftest test-partial-sample
  (let [stats (jstat-reader sample 2 (resource "jstat.txt"))]
    (is (= 2 (.size stats)))

    (is (= 1.0 ((stats 1) "Timestamp")))
    (is (= 2.0 ((stats 1) "PC")))
    (is (= 3.0 ((stats 1) "PU")))
    (is (= 4.0 ((stats 1) "OC")))
    (is (= 5.0 ((stats 1) "OU")))
    (is (= 6.0 ((stats 1) "YGC")))
    (is (= 7.0 ((stats 1) "FGC")))
    (is (= 8.0 ((stats 1) "FGCT")))
    (is (= 9.0 ((stats 1) "GCT")))

    (is (= 3.0 ((stats 3) "Timestamp")))
    (is (= 4.0 ((stats 3) "PC")))
    (is (= 5.0 ((stats 3) "PU")))
    (is (= 6.0 ((stats 3) "OC")))
    (is (= 7.0 ((stats 3) "OU")))
    (is (= 8.0 ((stats 3) "YGC")))
    (is (= 9.0 ((stats 3) "FGC")))
    (is (= 10.0 ((stats 3) "FGCT")))
    (is (= 11.0 ((stats 3) "GCT")))
    )
  )

(deftest test-mean
  (let [stats (jstat-reader mean 2 (resource "jstat.txt"))]
    (is (= 2 (.size stats)))

    (is (= (long (/ (+ 1 2) 2)) ((stats 1) "Timestamp")))
    (is (= (long (/ (+ 2 3) 2)) ((stats 1) "PC")))
    (is (= (long (/ (+ 3 4) 2)) ((stats 1) "PU")))
    (is (= (long (/ (+ 4 5) 2)) ((stats 1) "OC")))
    (is (= (long (/ (+ 5 6) 2)) ((stats 1) "OU")))
    (is (= (long (/ (+ 6 7) 2)) ((stats 1) "YGC")))
    (is (= (long (/ (+ 7 8) 2)) ((stats 1) "FGC")))
    (is (= (long (/ (+ 8 9) 2)) ((stats 1) "FGCT")))
    (is (= (long (/ (+ 9 10) 2)) ((stats 1) "GCT")))

    (is (= (long (/ (+ 3 4) 2)) ((stats 2) "Timestamp")))
    (is (= (long (/ (+ 4 5) 2)) ((stats 2) "PC")))
    (is (= (long (/ (+ 5 6) 2)) ((stats 2) "PU")))
    (is (= (long (/ (+ 6 7) 2))((stats 2) "OC")))
    (is (= (long (/ (+ 7 8) 2)) ((stats 2) "OU")))
    (is (= (long (/ (+ 8 9) 2)) ((stats 2) "YGC")))
    (is (= (long (/ (+ 9 10) 2)) ((stats 2) "FGC")))
    (is (= (long (/ (+ 10 11) 2)) ((stats 2) "FGCT")))
    (is (= (long (/ (+ 11 12) 2)) ((stats 2) "GCT")))
    )
  )

